### ISSUE TITLE
'bool' object is not iterable

### ISSUE THREAD

**Issue by Sam1370** [stephanpieterse/pyblend-animidi#1]
I'm having this issue when trying to use the program:
`Currently running for config.yml ...
starting script...
making ticks relative...
reading track 0 of 0
built track 0
mapping data to objects...
clearing the script output file...
Traceback (most recent call last):
  File "pyblend-animidi.py", line 91, in <module>
    main(sys.argv[1:])
  File "pyblend-animidi.py", line 84, in main
    gen_script.main()
  File "C:\Users\sampi\Desktop\pyblend-animidi-master\main.py", line 257, in main
    for cset in cycleConfs:
TypeError: 'bool' object is not iterable`

**Comment by Sam1370** [comment]
Just wanted to show this for users who are getting this problem. You may close if you want (or ask me, I'll close it)

**Comment by Sam1370** [comment]
Haha i found the problem. I put `cycleSequences` instead of `cycle_sequences`
